import smartpy as sp  # type: ignore

Categories = {
    "go": "go",
    "property_a": "property_a",
    "community_chest": "community_chest",
    "tax": "tax",
    "utility": "utility",
    "property_b": "property_b",
    "chance": "chance",
    "property_c": "property_c",
    "utility": "utility",
    "property_d": "property_d",
    "free_parking": "free_parking",
    "property_e": "property_e",
    "property_f": "property_f",
    "go_to_jail": "go_to_jail",
    "property_g": "property_g",
    "property_h": "property_h",
    "jail": "jail",
}


Spaces = sp.big_map(
    l={
        1: sp.record(name="go", category=Categories["go"]),
        2: sp.record(name="Mediterranean Avenue", category=Categories["property_a"]),
        3: sp.record(name="Community Chest", category=Categories["community_chest"]),
        4: sp.record(name="Baltic Avenue", category=Categories["property_a"]),
        5: sp.record(name="Income tax", category=Categories["tax"]),
        6: sp.record(name="Reading utility", category=Categories["utility"]),
        7: sp.record(name="Oriental Avenue", category=Categories["property_b"]),
        8: sp.record(name="chance", category=Categories["chance"]),
        9: sp.record(name="Vermont Avenue", category=Categories["property_b"]),
        10: sp.record(name="Connecticut Avenue", category=Categories["property_b"]),
        11: sp.record(name="jail", category=Categories["jail"]),
        12: sp.record(name="St. Charles Place", category=Categories["property_c"]),
        13: sp.record(name="Electric Company", category=Categories["utility"]),
        14: sp.record(name="States Avenue", category=Categories["property_c"]),
        15: sp.record(name="Virginia Avenue", category=Categories["property_c"]),
        16: sp.record(name="Pennsylvania utility", category=Categories["utility"]),
        17: sp.record(name="St. James Place", category=Categories["property_d"]),
        18: sp.record(name="Community Chest", category=Categories["community_chest"]),
        19: sp.record(name="Tennessee Avenue", category=Categories["property_d"]),
        20: sp.record(name="New York Avenue", category=Categories["property_d"]),
        21: sp.record(name="Free Parking", category=Categories["free_parking"]),
        22: sp.record(name="Kentucky Avenue", category=Categories["property_e"]),
        23: sp.record(name="chance", category=Categories["chance"]),
        24: sp.record(name="Indiana Avenue", category=Categories["property_e"]),
        25: sp.record(name="Illinois Avenue", category=Categories["property_e"]),
        26: sp.record(name="B. & O. utility", category=Categories["utility"]),
        27: sp.record(name="Atlantic Avenue", category=Categories["property_f"]),
        28: sp.record(name="Ventnor Avenue", category=Categories["property_f"]),
        29: sp.record(name="Water Works", category=Categories["utility"]),
        30: sp.record(name="Marvin Gardens", category=Categories["property_f"]),
        31: sp.record(name="go To jail", category=Categories["go_to_jail"]),
        32: sp.record(name="Pacific Avenue", category=Categories["property_g"]),
        33: sp.record(name="North Carolina Avenue", category=Categories["property_g"]),
        34: sp.record(name="Community Chest", category=Categories["community_chest"]),
        35: sp.record(name="Pennsylvania Avenue", category=Categories["property_g"]),
        36: sp.record(name="Short Line", category=Categories["utility"]),
        37: sp.record(name="chance", category=Categories["chance"]),
        38: sp.record(name="Park Place", category=Categories["property_h"]),
        39: sp.record(name="Luxury tax", category=Categories["tax"]),
        40: sp.record(name="Boardwalk", category=Categories["property_h"]),
    },
    tkey=sp.TNat,
    tvalue=sp.TRecord(name=sp.TString, category=sp.TString),
)
