import smartpy as sp  # type: ignore

Categories = {
    "Go": "Go",
    "Brown": "Brown",
    "CommunityChest": "CommunityChest",
    "Tax": "Tax",
    "Railroad": "Railroad",
    "LightBlue": "LightBlue",
    "Chance": "Chance",
    "Pink": "Pink",
    "Utility": "Utility",
    "Orange": "Orange",
    "FreeParking": "FreeParking",
    "Red": "Red",
    "Yellow": "Yellow",
    "GoToJail": "GoToJail",
    "Green": "Green",
    "DarkBlue": "DarkBlue",
    "Jail": "Jail",
}


Spaces = sp.big_map(
    l={
        1: sp.record(name="Go", category=Categories["Go"]),
        2: sp.record(name="Mediterranean Avenue", category=Categories["Brown"]),
        3: sp.record(name="Community Chest", category=Categories["CommunityChest"]),
        4: sp.record(name="Baltic Avenue", category=Categories["Brown"]),
        5: sp.record(name="Income Tax", category=Categories["Tax"]),
        6: sp.record(name="Reading Railroad", category=Categories["Railroad"]),
        7: sp.record(name="Oriental Avenue", category=Categories["LightBlue"]),
        8: sp.record(name="Chance", category=Categories["Chance"]),
        9: sp.record(name="Vermont Avenue", category=Categories["LightBlue"]),
        10: sp.record(name="Connecticut Avenue", category=Categories["LightBlue"]),
        11: sp.record(name="Jail", category=Categories["Jail"]),
        12: sp.record(name="St. Charles Place", category=Categories["Pink"]),
        13: sp.record(name="Electric Company", category=Categories["Utility"]),
        14: sp.record(name="States Avenue", category=Categories["Pink"]),
        15: sp.record(name="Virginia Avenue", category=Categories["Pink"]),
        16: sp.record(name="Pennsylvania Railroad", category=Categories["Railroad"]),
        17: sp.record(name="St. James Place", category=Categories["Orange"]),
        18: sp.record(name="Community Chest", category=Categories["CommunityChest"]),
        19: sp.record(name="Tennessee Avenue", category=Categories["Orange"]),
        20: sp.record(name="New York Avenue", category=Categories["Orange"]),
        21: sp.record(name="Free Parking", category=Categories["FreeParking"]),
        22: sp.record(name="Kentucky Avenue", category=Categories["Red"]),
        23: sp.record(name="Chance", category=Categories["Chance"]),
        24: sp.record(name="Indiana Avenue", category=Categories["Red"]),
        25: sp.record(name="Illinois Avenue", category=Categories["Red"]),
        26: sp.record(name="B. & O. Railroad", category=Categories["Railroad"]),
        27: sp.record(name="Atlantic Avenue", category=Categories["Yellow"]),
        28: sp.record(name="Ventnor Avenue", category=Categories["Yellow"]),
        29: sp.record(name="Water Works", category=Categories["Utility"]),
        30: sp.record(name="Marvin Gardens", category=Categories["Yellow"]),
        31: sp.record(name="Go To Jail", category=Categories["GoToJail"]),
        32: sp.record(name="Pacific Avenue", category=Categories["Green"]),
        33: sp.record(name="North Carolina Avenue", category=Categories["Green"]),
        34: sp.record(name="Community Chest", category=Categories["CommunityChest"]),
        35: sp.record(name="Pennsylvania Avenue", category=Categories["Green"]),
        36: sp.record(name="Short Line", category=Categories["Railroad"]),
        37: sp.record(name="Chance", category=Categories["Chance"]),
        38: sp.record(name="Park Place", category=Categories["DarkBlue"]),
        39: sp.record(name="Luxury Tax", category=Categories["Tax"]),
        40: sp.record(name="Boardwalk", category=Categories["DarkBlue"]),
    },
    tkey=sp.TNat,
    tvalue=sp.TRecord(name=sp.TString, category=sp.TString),
)
