on: [push]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tezworld-compile-send-notification:
    runs-on: ubuntu-latest
    steps:

      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true

      - name: install modules
        run: |
          npm update
          npm ci

      - name: compile contracts
        uses: ecadlabs/taqueria-github-action@v0.13.0
        with:
            compile_contracts: "dealer.py, players.py, tezcredits.py, board.py"
            compile_plugin: smartpy

      # 1
      # - name: Send GitHub notification
      #   uses: fateyan/action-discord-notifier@v1
      #   with:
      #     message-title: New Code Pushed
      #     webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}

      # 2
      # - name: Notify on discord
      #   uses: th0th/notify-discord@v0.4.1
      #   if: ${{ always() }}
      #   env:
      #     DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      #     GITHUB_ACTOR: ${{ github.actor }}
      #     GITHUB_JOB_NAME: "Code Built Successfully"
      #     GITHUB_JOB_STATUS: ${{ job.status }}

      - name: Send Discord notification
        uses: stegzilla/discord-notify@v2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: ${{GITHUB_ACTION}}
          message: "Code Built Successfully at ${{GITHUB_REPOSITORY}} by ${{GITHUB_ACTOR}" 
          include_image: true
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          username: ${{ GITHUB_ACTOR }}