on: [push]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tezworld-compile:
    runs-on: ubuntu-latest
    steps:

      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true

      - name: install modules
        run: |
          npm update
          npm ci

      - name: compile contracts
        uses: ecadlabs/taqueria-github-action@v0.13.0
        with:
            compile_contracts: "dealer.py, player.py, tezcredits.py, board.py"
            compile_plugin: smartpy
